### ISSUE TITLE
Better example in documentation

### ISSUE THREAD

**Issue by Tecktron** [ember-cli-deploy/ember-cli-deploy-ssh-tunnel#2]
It's not very obvious that you have to or how to use the context to obtain the auto-generated srcPort without going through your source and basically learning how to write a plugin, not something I really wanted to do in order to get a deployment pushed out in a hurry (having taken over a project). It should be simply stated in the readme file.

**Comment by ghedamat** [comment]
@Tecktron sorry that you found it confusing, as specified in the options you can force the port to be whatever you like instead of relying on the random one,

using context is intended more for other plugin users that need to access the port itself.

If you're willing to provide an PR/addition to the README that could clarify what you were expecting to see we'll be happy to merge it.

maybe we should point users to this complete example config that we use in the demo app

https://github.com/ghedamat/ember-deploy-demo/blob/master/edd-cli/config/deploy.js

**Comment by Tecktron** [comment]
@ghedamat Thanks, I eventually figured that out from playing around. I'm a bit confused and curious as to why you bothered with the random port functionality and not just force the user to use a port, if you're not going to explain how to use it. Well, if I get some time, I'll see if I can't figure out the context bit and add some documentation to this and also more comments to that demo. It's not as obvious as it could be until you've been through it quite a few bit.

Thanks for your time.

**Comment by ghedamat** [comment]
@Tecktron this plugin was extracted from a previous version of the redis adapter and the functionality was ported from there when we split it into separate plugins for the new version of ember-cli-deploy.

I feel that having explicit and documented options on how to set the ports is a decent start and I'd rather not make the `srcPort` option mandatory if it can be avoided.

If you end up being more curious on how to use the random port and the context object ping me on the #ember-cli-deploy channel of the ember community slack and maybe we can come up with a better explanation and a more useful example for the docs.
