### ISSUE TITLE
A way to "disable" this pipeline step in particular environments

### ISSUE THREAD

**Issue by mansona** [ember-cli-deploy/ember-cli-deploy-ssh-tunnel#6]
I've got this working for our live deployments (awesome btw :+1:) but I'm just trying to test something out locally and I feel like I have to fight against this plugin to get it to work.

The key fact is that I just don't want it to run when I am running a deployment environment deploy and it feels odd that in these cases it is complaining that `username` and `host` are required. I don't know if this sort of API is supported by ember-cli-deploy but it would be great if you could add the following config: 

```
if (deployTarget === 'development') {
    ENV['ssh-tunnel'] = {
      disabled: true
    };
  }
```

which not only disables the pipeline step but it also _prevents ember-cli-deploy from running validations on "required" parameters_. 

Just a thought :wink:

**Comment by achambers** [comment]
Hi @mansona. You can essentially do this with the `plugins` config property ([DOCS](http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/configuration-overview/))

By implementing this top level config property, you can override which plugins are run and in what order. You could implement this property for your dev environment only.

You will need to specify all the plugins you want to run (as opposed to saying which you don't) but you will be able to achieve what you want.

Please close this issue if you are happy with the above. Otherwise, we can open a discussion if you think there is more to talk about.

**Comment by ghedamat** [comment]
as a side discussion:

@achambers @lukemelia this makes me think, as we merged this https://github.com/ember-cli-deploy/ember-cli-deploy-slack/pull/10 for the slack plugin that adds an "enabled" property. 

Maybe specifying `plugins` is the way to go for this or maybe we want more `enabled` properties to pop up (with the problem that config will be validated as @mansona said), or maybe we want something slightly different for the `enabled` property..

**Comment by ghedamat** [comment]
or, shall we add an `excludedPlugins` property that complements the other one? maybe this is the nicer way..

**Comment by achambers** [comment]
@ghedamat I think I prefer something like `excludedPlugins` over `enabled` inside each plugin config....Would like to explore that.

Not sure how that plays out with `plugins`. Does that needs to be renamed `includedPlugins`. What happens if you have the same plugin listed in both arrays? How does aliasing of plugins work?

**Comment by ghedamat** [comment]
@achambers agreed, leaking `enabled` everywhere sound a bad idea.

maybe I'm oversimplifying but I was thinking that `excludedPlugins` would be used **only** if `plugins` is not defined and ignored otherwise.

**Comment by lukemelia** [comment]
@ghedamat @achambers I will open an issue on ember-cli-deploy and we can
hash it out there.

**Comment by lukemelia** [comment]
Turns out we already have
https://github.com/ember-cli/ember-cli-deploy/issues/307

**Comment by ghedamat** [comment]
haha :D  ERR:TOOMANYREPOS

**Comment by ghedamat** [comment]
@mansona please reopen if needed otherwise let's keep the discussion on the main repo.

thanks!

**Comment by mansona** [comment]
Wow thanks everyone! No need to reopen, this discussion essentially answers my question and I'll hop on the main issue :+1: 

Thanks again everyone 🎉
